
export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  kind?: string; // 'asr' for auto-generated, undefined for manual
  isAutoGenerated: boolean;
}

export interface TranscriptStrategy {
  name: string;
  fetchTranscript(videoId: string): Promise<string>;
}

export interface ProcessedTranscript {
  success: boolean;
  transcript: string;
  metadata: {
    segments: number;
    duration: number;
    hasTimestamps: boolean;
    source: string;
    language: string;
    videoId: string;
    extractionMethod: string;
  };
  error?: string;
}

export interface StrategyResult {
  success: boolean;
  data?: string;
  error?: string;
  strategy: string;
}
