
project_id = "rqxhgeujepdhhzoaeomu"

[functions.fetch-youtube-transcript]
verify_jwt = true

[functions.process-content-with-deepseek]
verify_jwt = true

[functions.enhanced-youtube-processor]
verify_jwt = true

[functions.youtube-metadata]
verify_jwt = true

[functions.tesseract-ocr]
verify_jwt = true

[functions.mistral-ocr-processor]
verify_jwt = true
