// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqxhgeujepdhhzoaeomu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxeGhnZXVqZXBkaGh6b2Flb211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Mjg4MjMsImV4cCI6MjA2MzUwNDgyM30.nXAsuClyrleY5I55yXBFH0q0L3KY6K7utBfv98UjJmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);